### ISSUE TITLE
Control Inversion per Monitor

### ISSUE THREAD

**Issue by JohnTravolski** [mlaily/NegativeScreen#29] opened 2023-04-06 02:01 UTC
Is it possible to limit which monitor the inversion occurs on? For example, suppose I have a dark mode program on monitor 1 and a light mode program on monitor 2. It would be great if I could somehow limit the inversion to monitor 2. Is this possible?

**Comment by mlaily** [comment] 2023-04-07 06:04
Duplicate of https://github.com/mlaily/NegativeScreen/issues/2

**Closed as not planned by mlaily** 2023-04-07 06:04 UTC
